### ISSUE TITLE
wakatime JSON

### ISSUE THREAD

**Issue by zeke** [simonkberg/simon-kjellberg#15]
Hi. @simonkberg. Pretty nifty code stats on https://simonkjellberg.com ✨ 💻 ✨ 

How are you generating these URLs?

https://github.com/simonkberg/simon-kjellberg/blob/042a6d82a93a28763e1da251067d97b5045eaa5a/server/api/waka-time.js#L4

**Comment by zeke** [comment]
cc @alanhamlett

**Comment by alanhamlett** [comment]
You can get a personal shareable url here:
https://wakatime.com/share

**Comment by zeke** [comment]
Nice!

It's working fine now, but I got this blip for a moment:

![screen shot 2016-07-12 at 4 24 06 pm](https://cloud.githubusercontent.com/assets/2289/16786911/3653a58a-484d-11e6-8613-9cf695a36e07.png)
